### ISSUE TITLE
class instead of data-iconfig

### ISSUE THREAD

**Issue by wini2** [quellenform/t3x-iconpack-bootstrap#1]
hi,

I want to use this ext the first time, installation works but I'm a little suprised that I get a span with data-iconfig-attribute. Is there a way to substitue this with class?

**Comment by stephankellermayr** [comment]
The default CSS class is "iconpack". This can be changed to your needs. More information can be found here: https://docs.typo3.org/p/quellenform/t3x-iconpack/main/en-us/

**Comment by wini2** [comment]
Thanks for your help; I overlooked the crucial line 'If you want to keep the default settings, simply add the TypoScript provided **at the end** of your setup:'
